AUTOCOMMIT OFF;

DROP TABLE ACHAT;
DROP TABLE BOUTIQUE;
DROP TABLE CATEGORIE;
DROP TABLE COMMANDE;
DELETE FROM EJB__TIMER__TBL;
DROP TABLE ENCHERE;
DROP TABLE ENCHEREGAGNEE;
DROP TABLE IMAGE;
DROP TABLE NOTEPRODUIT;
DROP TABLE NOTETRANSACTION;
DROP TABLE PANIER;
DROP TABLE PANIER_ENCHERE;
DROP TABLE PANIER_PRODUITPANIER;
DROP TABLE PRODUIT;
DROP TABLE PRODUITPANIER;
DROP TABLE PRODUIT_IMAGE;
DROP TABLE SEQUENCE;
DROP TABLE UTILISATEUR;
DROP TABLE VENTEIMMEDIATE;

COMMIT;


